services:
  flask:
    build: backend/
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file: 
      - .env

  react:
    build: frontend/
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - flask
    environment:
      - REACT_APP_API_URL=http://flask:5000